// <auto-generated />
using System;
using AbsenDulu.BE.Database.Helper.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AbsenDulu.BE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230916040357_migrate14")]
    partial class migrate14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbsenDulu.BE.Models.Activation.UserActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activation_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_activated");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_activation");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Attendances.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttendanceImage")
                        .HasColumnType("text")
                        .HasColumnName("attendance_image");

                    b.Property<string>("AttendanceMethod")
                        .HasColumnType("text")
                        .HasColumnName("attendance_method");

                    b.Property<string>("AttendanceType")
                        .HasColumnType("text")
                        .HasColumnName("attendance_type");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeShift")
                        .HasColumnType("text")
                        .HasColumnName("employee_shift");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("Latitude")
                        .HasColumnType("text")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("text")
                        .HasColumnName("location_address");

                    b.Property<string>("Longitude")
                        .HasColumnType("text")
                        .HasColumnName("longitude");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("attendance");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Attendances.AttendanceView", b =>
                {
                    b.Property<string>("ClockIn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_in");

                    b.Property<string>("ClockInAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_in_address");

                    b.Property<string>("ClockInMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_in_method");

                    b.Property<string>("ClockInNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_in_note");

                    b.Property<string>("ClockOut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_out");

                    b.Property<string>("ClockOutAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_out_address");

                    b.Property<string>("ClockOutMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_out_method");

                    b.Property<string>("ClockOutNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clock_out_note");

                    b.Property<string>("ClockinPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clockin_photo");

                    b.Property<string>("ClockoutPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clockout_photo");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmployeeShift")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_shift");

                    b.ToTable("view_attendances");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaCode")
                        .HasColumnType("text")
                        .HasColumnName("area_code");

                    b.Property<string>("AreaName")
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("master_area");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("master_department");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterLeave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("LeaveCode")
                        .HasColumnType("text")
                        .HasColumnName("leave_code");

                    b.Property<bool?>("LeaveMoreThanBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("leave_more_than_balance");

                    b.Property<string>("LeaveName")
                        .HasColumnType("text")
                        .HasColumnName("leave_name");

                    b.Property<int?>("TotalDays")
                        .HasColumnType("integer")
                        .HasColumnName("total_days");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("master_leave");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<string>("PositionCode")
                        .HasColumnType("text")
                        .HasColumnName("position_code");

                    b.Property<string>("PositionName")
                        .HasColumnType("text")
                        .HasColumnName("position_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("master_position");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterReimbusment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("ReimbusmentCode")
                        .HasColumnType("text")
                        .HasColumnName("reimbusment_code");

                    b.Property<string>("ReimbusmentName")
                        .HasColumnType("text")
                        .HasColumnName("reimbusment_name");

                    b.Property<int?>("TotalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_amount");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("master_reimbusment");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EndBreakTime")
                        .HasColumnType("text")
                        .HasColumnName("end_break_time");

                    b.Property<string>("EndWorkTime")
                        .HasColumnType("text")
                        .HasColumnName("end_work_time");

                    b.Property<string>("ShiftCode")
                        .HasColumnType("text")
                        .HasColumnName("shift_code");

                    b.Property<string>("ShiftName")
                        .HasColumnType("text")
                        .HasColumnName("shift_name");

                    b.Property<string>("StartBreakTime")
                        .HasColumnType("text")
                        .HasColumnName("start_break_time");

                    b.Property<string>("StartWorkTime")
                        .HasColumnType("text")
                        .HasColumnName("start_work_time");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string[]>("WorkDays")
                        .HasColumnType("text[]")
                        .HasColumnName("work_days");

                    b.HasKey("Id");

                    b.ToTable("master_shift");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Company.MasterWorkshop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkshopCode")
                        .HasColumnType("text")
                        .HasColumnName("workshop_code");

                    b.Property<string>("WorkshopName")
                        .HasColumnType("text")
                        .HasColumnName("workshop_name");

                    b.HasKey("Id");

                    b.ToTable("master_workshop");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Employee.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountTypeid")
                        .HasColumnType("integer")
                        .HasColumnName("account_type_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AreaCode")
                        .HasColumnType("text")
                        .HasColumnName("area_code");

                    b.Property<string>("AreaName")
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text")
                        .HasColumnName("bank_account");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime?>("BpjsEmployeeEndPay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bpjs_employee_end_pay");

                    b.Property<string>("BpjsEmployeeNo")
                        .HasColumnType("text")
                        .HasColumnName("bpjs_employee_no");

                    b.Property<DateTime?>("BpjsEmployeeStartPay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bpjs_employee_start_pay");

                    b.Property<DateTime?>("BpjsHealthCareEndPay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bpjs_health_care_end_pay");

                    b.Property<string>("BpjsHealthCareNo")
                        .HasColumnType("text")
                        .HasColumnName("bpjs_health_care_no");

                    b.Property<DateTime?>("BpjsHealthCareStartPay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bpjs_health_care_start_pay");

                    b.Property<Guid>("CompanyCode")
                        .HasColumnType("uuid")
                        .HasColumnName("company_code");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<string>("DevicePhoto")
                        .HasColumnType("text")
                        .HasColumnName("device_photo");

                    b.Property<DateTime?>("EffectiveEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_end");

                    b.Property<DateTime?>("EffectiveStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_start");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("text")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmployeeTypeCode")
                        .HasColumnType("text")
                        .HasColumnName("employee_type_code");

                    b.Property<string>("EmployeeTypeName")
                        .HasColumnType("text")
                        .HasColumnName("employee_type_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsResign")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resign");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_date");

                    b.Property<string>("NPWPNo")
                        .HasColumnType("text")
                        .HasColumnName("npwp_no");

                    b.Property<string>("National")
                        .HasColumnType("text")
                        .HasColumnName("national");

                    b.Property<string>("PIC")
                        .HasColumnType("text")
                        .HasColumnName("pic");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PositionCode")
                        .HasColumnType("text")
                        .HasColumnName("position_code");

                    b.Property<string>("PositionName")
                        .HasColumnType("text")
                        .HasColumnName("position_name");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.Property<DateTime?>("ResignDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resign_date");

                    b.Property<DateTime?>("TaxEndPay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tax_end_pay");

                    b.Property<DateTime?>("TaxStartPay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tax_start_pay");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("WorkTypeId")
                        .HasColumnType("text")
                        .HasColumnName("work_type_id");

                    b.Property<string>("WorkTypeName")
                        .HasColumnType("text")
                        .HasColumnName("work_type_name");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.LogError.LogErrorAbsenDulu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.ToTable("log_error_absendulu");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.Subcribes.DetailSubcribe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("apps_total");

                    b.Property<int>("AppsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("apps_used");

                    b.Property<DateTime>("CompanyExpiredSubcribe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("company_expired_subcribe");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CompanyStartSubcribe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("company_start_subcribe");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DeviceTotal")
                        .HasColumnType("integer")
                        .HasColumnName("device_total");

                    b.Property<int>("DeviceUsed")
                        .HasColumnType("integer")
                        .HasColumnName("device_used");

                    b.Property<int>("RemainingApps")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_apps");

                    b.Property<int>("RemainingDevice")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_device");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("details_subcribe");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.User.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AccountTypeid")
                        .HasColumnType("integer")
                        .HasColumnName("account_type_id");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_date");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("IpAddressUserLogin")
                        .HasColumnType("text")
                        .HasColumnName("ip_address_user_login");

                    b.Property<int>("IsActive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<int>("IsLock")
                        .HasColumnType("integer")
                        .HasColumnName("is_lock");

                    b.Property<int>("IsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user_account");
                });

            modelBuilder.Entity("AbsenDulu.BE.Models.User.UserResetPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("pin_code");

                    b.Property<string>("ResetPasswordCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reset_password_code");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_reset_password");
                });
#pragma warning restore 612, 618
        }
    }
}
